config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :cats
  
  root 'home#index'
  get 'about' => 'about#index'
  get 'users' => 'users#index'
  
  # USERS
  get 'sign_up' => 'registration#new'
  post 'sign_up' => 'registration#create'

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'password', to: 'password#edit', as: :edit_password
  patch 'password' => 'password#update'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	attribute :user
end 

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: {with: /\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})/, message: "Must be a valid email address"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_current_user

	def set_current_user
		if session[:user_id]
			Current.user = User.find_by(id: session[:user_id]) #app crash on find() if user is removed
		end
	end

	def require_user_logged_in
		redirect_to sign_in_path, alert: "You must be signed in to continue!" if Current.user.nil?
	end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]

  # GET /cats or /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1 or /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats or /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully created." }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1 or /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully updated." }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1 or /cats/1.json
  def destroy
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to cats_url, notice: "Cat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.require(:cat).permit(:name, :age)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
	before_action :require_user_logged_in
	def edit
end

def update
	if Current.user.update(password_params)
		redirect_to root_path, notice: "You have successfully changed password"
	else
		render :edit
	end
end

private

def password_params
	params.require(:user).permit(:password, :password_confirmation)
end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, notice:"Succesfully created user"
		else
			render :new
		end
	end

    def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:email])

		if user.present? && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path, notice: "Sucessfully logged in"
		else
			flash[:alert] = "Invalid email or password"
			render :new
		end
	end

	def destroy 
		session[:user_id] = nil
		redirect_to root_path, notice: "Logged out"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1>About Page</h1>

app/views/cats/_cat.html.erb
<div id="<%= dom_id cat %>">
  <p>
    <strong>Name:</strong>
    <%= cat.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= cat.age %>
  </p>

</div>

app/views/cats/_form.html.erb
<%= form_with(model: cat) do |form| %>
  <% if cat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
        <% cat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Show this cat", @cat %> |
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cats</h1>

<div id="cats">
  <% @cats.each do |cat| %>
    <%= render cat %>
    <p>
      <%= link_to "Show this cat", cat %>
    </p>
  <% end %>
</div>

<%= link_to "New cat", new_cat_path %>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cat %>

<div>
  <%= link_to "Edit this cat", edit_cat_path(@cat) %> |
  <%= link_to "Back to cats", cats_path %>

  <%= button_to "Destroy this cat", @cat, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Välkommen</h1>

<% if Current.user %>
	<p> Logged in as <%= Current.user.email %> <p> 
	<%#= link_to "Logout", logout_path, method: :delete %>
	<%= button_to "Logout", logout_path, method: :delete, class: "btn btn-secondary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyonrailsTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render partial:"shared/navbar" %>
    
    <div class='container'>
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/password/edit.html.erb
<h1>Edit password</h1>

<%= form_with model: Current.user, data: { turbo: false }, url:edit_password_path do |form| %>
	<% if form.object.errors.any? %>
		<div class="alert alert-danger">
			<% form.object.errors.full_messages.each do |message|%>
				<div>
					<%= message %>
				</div>
				<% end %>
		</div>
	<% end %>

	<div class="mb-3">
		<%= form.label :password %>
		<%= form.password_field :password, class: "form-control" , placeholder: "new password" %>
	</div>

	<div class="mb-3">
		<%= form.label :password_confirmation %>
		<%= form.password_field :password_confirmation, class: "form-control" , placeholder: "new password" %>
	</div>

	<div>
		<%= form.submit "Update Password" , class: "btn btn-primary" %>
	</div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info mt4" role="alert">
		<%= flash[:notice] %>
	</div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-warning mt4" role="alert">
		<%= flash[:alert] %>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Muppet</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%=link_to "Home", root_path, class: "nav-link" %>
        </li>
              <li class="nav-item">

          <%=link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item" >
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%=button_to "Logout", logout_path, method: :delete, class: "btn btn-outliuned-secondary" %>
          </li>
        <%  else %>
          <li class="nav-item">
            <%=link_to "Sign up", sign_up_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%=link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
        <%end%>
      </ul>

    </div>
  </div>
</nav>

app/views/shared/_user_registration.html.erb
<%= form_with model: @user do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

<br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, url:sign_up_path) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "example@mail.com" %>
  </div>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
  </div>

  <div>
    <%= form.submit "Sign Up", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users" >
  <% @users.each do |user| %>
    <div class="p-3 bg-primary mb-3 text-white">
      <%= render user %>
        <p>
          <%= link_to "Show this user", user,  class: "text-white" %>
        </p>
    </div>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>